apiVersion: apps/v1
kind: Deployment
metadata:
  name: fyp-thong-wan-hin
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      component: iothub
      student: thong-wan-hin
  template:
    metadata:
      labels:
        component: iothub
        student: thong-wan-hin
    spec:
      containers:
        - name: iothub
          image: hinccvi/fyp:v0.3
          resources:
            limits:
              cpu: 50m
              memory: 64Mi
              ephemeral-storage: 64Mi
            requests:
              cpu: 50m
              memory: 64Mi